// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
	/**
	 * Title field in *Article*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: e.g. Why You Should Read The Bible
	 * - **API ID Path**: article.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Image field in *Article*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Author field in *Article*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: Select an author...
	 * - **API ID Path**: article.author
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	author: prismic.ContentRelationshipField<"author">;

	/**
	 * description field in *Article*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: e.g. The first sentence of the article
	 * - **API ID Path**: article.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Content field in *Article*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<ArticleDocumentData>,
		"article",
		Lang
	>;

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
	/**
	 * Name field in *Author*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: e.g. John Doe
	 * - **API ID Path**: author.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;

	/**
	 * Description field in *Author*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Write a few sentences about the author...
	 * - **API ID Path**: author.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Image field in *Author*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: author.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<AuthorDocumentData>,
		"author",
		Lang
	>;

/**
 * Content for Button documents
 */
interface ButtonDocumentData {
	/**
	 * Title field in *Button*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: button.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Link field in *Button*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: button.link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Description field in *Button*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: button.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Button document from Prismic
 *
 * - **API ID**: `button`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ButtonDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<ButtonDocumentData>,
		"button",
		Lang
	>;

/**
 * Content for Event documents
 */
interface EventDocumentData {
	/**
	 * Title field in *Event*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Image field in *Event*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Date and time field in *Event*
	 *
	 * - **Field Type**: Timestamp
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.date_and_time
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#timestamp
	 */
	date_and_time: prismic.TimestampField;

	/**
	 * Address field in *Event*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: e.g. Neal St Espresso, WC2H 9PS
	 * - **API ID Path**: event.address
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	address: prismic.KeyTextField;

	/**
	 * Content field in *Event*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;

	/**
	 * Eventbrite URL field in *Event*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.eventbrite_url
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	eventbrite_url: prismic.LinkField;
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;

/**
 * Content for Highlighted Event documents
 */
interface HighlightedEventDocumentData {
	/**
	 * Event field in *Highlighted Event*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlighted_event.event
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	event: prismic.ContentRelationshipField<"event">;

	/**
	 * Visibility field in *Highlighted Event*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: highlighted_event.visibility
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	visibility: prismic.BooleanField;

	/**
	 * Finish Timestamp field in *Highlighted Event*
	 *
	 * - **Field Type**: Timestamp
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlighted_event.finish_timestamp
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#timestamp
	 */
	finish_timestamp: prismic.TimestampField;
}

/**
 * Highlighted Event document from Prismic
 *
 * - **API ID**: `highlighted_event`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HighlightedEventDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<HighlightedEventDocumentData>,
		"highlighted_event",
		Lang
	>;

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for home documents
 */
interface HomeDocumentData {
	/**
	 * Slice Zone field in *home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
	 * Meta Description field in *home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: home.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *home*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: home.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Podcast documents
 */
interface PodcastDocumentData {
	/**
	 * Title field in *Podcast*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: e.g. Aaron Edwards Interview
	 * - **API ID Path**: podcast.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Image field in *Podcast*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: podcast.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Description field in *Podcast*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Write a couple of sentences about the episode or the interviewee.
	 * - **API ID Path**: podcast.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Youtube Video URL field in *Podcast*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: e.g. https://youtu.be/ABCDE_123
	 * - **API ID Path**: podcast.youtube_video
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	youtube_video: prismic.LinkField;

	/**
	 * Audio URL field in *Podcast*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Attach the PUBLIC audio URL from Dropbox/Google Drive
	 * - **API ID Path**: podcast.audio_url
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	audio_url: prismic.LinkField;

	/**
	 * Original Date Published field in *Podcast*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: (This is US style - MM-DD-YYYY)
	 * - **API ID Path**: podcast.original_date_published
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	original_date_published: prismic.DateField;
}

/**
 * Podcast document from Prismic
 *
 * - **API ID**: `podcast`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PodcastDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<PodcastDocumentData>,
		"podcast",
		Lang
	>;

/**
 * Item in *Walk → Historical Characters*
 */
export interface WalkDocumentDataHistoricalCharactersItem {}

/**
 * Item in *Walk → Locations*
 */
export interface WalkDocumentDataLocationsItem {}

type WalkDocumentDataSlicesSlice = never;

/**
 * Content for Walk documents
 */
interface WalkDocumentData {
	/**
	 * Title field in *Walk*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: walk.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Price (GBP) field in *Walk*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: walk.price
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price: prismic.NumberField;

	/**
	 * Historical Characters field in *Walk*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: walk.historical_characters[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	historical_characters: prismic.GroupField<
		Simplify<WalkDocumentDataHistoricalCharactersItem>
	>;

	/**
	 * Duration (hours) field in *Walk*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: walk.duration
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	duration: prismic.NumberField;

	/**
	 * Locations field in *Walk*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: walk.locations[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	locations: prismic.GroupField<Simplify<WalkDocumentDataLocationsItem>>;

	/**
	 * Image field in *Walk*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: walk.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Slice Zone field in *Walk*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: walk.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<WalkDocumentDataSlicesSlice>;
}

/**
 * Walk document from Prismic
 *
 * - **API ID**: `walk`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WalkDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<Simplify<WalkDocumentData>, "walk", Lang>;

export type AllDocumentTypes =
	| ArticleDocument
	| AuthorDocument
	| ButtonDocument
	| EventDocument
	| HighlightedEventDocument
	| HomeDocument
	| PodcastDocument
	| WalkDocument;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
	/**
	 * Description field in *CallToAction → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Button field in *CallToAction → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.primary.button
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button: prismic.ContentRelationshipField<"button">;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<CallToActionSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
	"call_to_action",
	CallToActionSliceVariation
>;

/**
 * Primary content in *Lattice → Items*
 */
export interface CardColumnsSliceDefaultItem {
	/**
	 * Card field in *Lattice → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_columns.items[].card
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	card: prismic.ContentRelationshipField;
}

/**
 * Default variation for Lattice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardColumnsSliceDefault = prismic.SharedSliceVariation<
	"default",
	Record<string, never>,
	Simplify<CardColumnsSliceDefaultItem>
>;

/**
 * Primary content in *Lattice → Items*
 */
export interface CardColumnsSliceWalkingTourCardsItem {
	/**
	 * Card field in *Lattice → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_columns.items[].card
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	card: prismic.ContentRelationshipField;
}

/**
 * WalkingTourCards variation for Lattice Slice
 *
 * - **API ID**: `walkingTourCards`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardColumnsSliceWalkingTourCards = prismic.SharedSliceVariation<
	"walkingTourCards",
	Record<string, never>,
	Simplify<CardColumnsSliceWalkingTourCardsItem>
>;

/**
 * Slice variation for *Lattice*
 */
type CardColumnsSliceVariation =
	| CardColumnsSliceDefault
	| CardColumnsSliceWalkingTourCards;

/**
 * Lattice Shared Slice
 *
 * - **API ID**: `card_columns`
 * - **Description**: CardColumns
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardColumnsSlice = prismic.SharedSlice<
	"card_columns",
	CardColumnsSliceVariation
>;

/**
 * Primary content in *Feature → Primary*
 */
export interface FeatureSliceDefaultPrimary {
	/**
	 * Title field in *Feature → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Author field in *Feature → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature.primary.author
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	author: prismic.ContentRelationshipField<"author">;

	/**
	 * Embed field in *Feature → Primary*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature.primary.embed
	 * - **Documentation**: https://prismic.io/docs/field#embed
	 */
	embed: prismic.EmbedField;

	/**
	 * Image field in *Feature → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Body field in *Feature → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Primary content in *Feature → Items*
 */
export interface FeatureSliceDefaultItem {
	/**
	 * Button field in *Feature → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature.items[].button
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button: prismic.ContentRelationshipField<"button">;
}

/**
 * Default variation for Feature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<FeatureSliceDefaultPrimary>,
	Simplify<FeatureSliceDefaultItem>
>;

/**
 * Primary content in *Feature → Primary*
 */
export interface FeatureSliceImageOnRightPrimary {
	/**
	 * Title field in *Feature → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Author field in *Feature → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature.primary.author
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	author: prismic.ContentRelationshipField<"author">;

	/**
	 * Embed field in *Feature → Primary*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature.primary.embed
	 * - **Documentation**: https://prismic.io/docs/field#embed
	 */
	embed: prismic.EmbedField;

	/**
	 * Image field in *Feature → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Body field in *Feature → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Primary content in *Feature → Items*
 */
export interface FeatureSliceImageOnRightItem {
	/**
	 * Button field in *Feature → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature.items[].button
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button: prismic.ContentRelationshipField<"button">;
}

/**
 * ImageOnRight variation for Feature Slice
 *
 * - **API ID**: `imageOnRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureSliceImageOnRight = prismic.SharedSliceVariation<
	"imageOnRight",
	Simplify<FeatureSliceImageOnRightPrimary>,
	Simplify<FeatureSliceImageOnRightItem>
>;

/**
 * Slice variation for *Feature*
 */
type FeatureSliceVariation = FeatureSliceDefault | FeatureSliceImageOnRight;

/**
 * Feature Shared Slice
 *
 * - **API ID**: `feature`
 * - **Description**: Feature
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureSlice = prismic.SharedSlice<
	"feature",
	FeatureSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Video field in *Hero → Primary*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.video
	 * - **Documentation**: https://prismic.io/docs/field#embed
	 */
	video: prismic.EmbedField;

	/**
	 * Thumbnail field in *Hero → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.thumbnail
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	thumbnail: prismic.ImageField<never>;

	/**
	 * Title field in *Hero → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *Hero → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageSlideshow → Items*
 */
export interface ImageSlideshowSliceDefaultItem {
	/**
	 * Image field in *ImageSlideshow → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_slideshow.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageSlideshow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlideshowSliceDefault = prismic.SharedSliceVariation<
	"default",
	Record<string, never>,
	Simplify<ImageSlideshowSliceDefaultItem>
>;

/**
 * Slice variation for *ImageSlideshow*
 */
type ImageSlideshowSliceVariation = ImageSlideshowSliceDefault;

/**
 * ImageSlideshow Shared Slice
 *
 * - **API ID**: `image_slideshow`
 * - **Description**: ImageSlideshow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlideshowSlice = prismic.SharedSlice<
	"image_slideshow",
	ImageSlideshowSliceVariation
>;

/**
 * Primary content in *TextBlock → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
	/**
	 * Body field in *TextBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_block.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<TextBlockSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
	"text_block",
	TextBlockSliceVariation
>;

declare module "@prismicio/client" {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig,
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			ArticleDocument,
			ArticleDocumentData,
			AuthorDocument,
			AuthorDocumentData,
			ButtonDocument,
			ButtonDocumentData,
			EventDocument,
			EventDocumentData,
			HighlightedEventDocument,
			HighlightedEventDocumentData,
			HomeDocument,
			HomeDocumentData,
			HomeDocumentDataSlicesSlice,
			PodcastDocument,
			PodcastDocumentData,
			WalkDocument,
			WalkDocumentData,
			WalkDocumentDataHistoricalCharactersItem,
			WalkDocumentDataLocationsItem,
			WalkDocumentDataSlicesSlice,
			AllDocumentTypes,
			CallToActionSlice,
			CallToActionSliceDefaultPrimary,
			CallToActionSliceVariation,
			CallToActionSliceDefault,
			CardColumnsSlice,
			CardColumnsSliceDefaultItem,
			CardColumnsSliceWalkingTourCardsItem,
			CardColumnsSliceVariation,
			CardColumnsSliceDefault,
			CardColumnsSliceWalkingTourCards,
			FeatureSlice,
			FeatureSliceDefaultPrimary,
			FeatureSliceDefaultItem,
			FeatureSliceImageOnRightPrimary,
			FeatureSliceImageOnRightItem,
			FeatureSliceVariation,
			FeatureSliceDefault,
			FeatureSliceImageOnRight,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			ImageSlideshowSlice,
			ImageSlideshowSliceDefaultItem,
			ImageSlideshowSliceVariation,
			ImageSlideshowSliceDefault,
			TextBlockSlice,
			TextBlockSliceDefaultPrimary,
			TextBlockSliceVariation,
			TextBlockSliceDefault,
		};
	}
}
