// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
	call_to_action: dynamic(() => import("./CallToAction")),
	card_columns: dynamic(() => import("./Lattice")),
	feature: dynamic(() => import("./Feature")),
	hero: dynamic(() => import("./Hero")),
	image_slideshow: dynamic(() => import("./ImageSlideshow")),
	text_block: dynamic(() => import("./TextBlock")),
};
